---
- name: provision a software
  hosts: all
  become: true
  gather_facts: true
  tasks:

   - name: Upload splunk installation file
     copy: src=/opt/splunk-6.5.2-67571ef4b87d-Linux-x86_64.tgz  dest=/opt/

   - name: Untar splunk tarball
     unarchive:  src=/opt/splunk-6.5.2-67571ef4b87d-Linux-x86_64.tgz  dest=/opt/ copy=no

   - name: Install Splunk
     command: /opt/splunk/bin/splunk start --accept-license

   - name: Enable boot-start
     command: /opt/splunk/bin/splunk enable boot-start
